package: cookie_optin
version: '1.0.2'
author: bloep
supportpage: https://github.com/bloep/cookie_optin

# Seiten
page:
    title: 'Cookie Opt-In'
    icon: rex-icon fa-empire
    perm: cookie_optin[]
    subpages:
        configuration:
            title: 'translate:configuration'
            icon: rex-icon fa-cogs


requires:
    redaxo: '^5.0'
    packages:
        yform: '>=2.3'

installer_ignore:
    - .git
    
