package: cookie_optin
version: '1.0.1'
author: mynetworx
supportpage: https://github.com/mynetworx/cookie_optin
supportemail: entwicklung@mynetworx.de

# Seiten
page:
    title: 'Cookie Opt-In'
    icon: rex-icon fa-empire
    perm: cookie_optin[]
    subpages:
        configuration:
            title: 'translate:configuration'
            icon: rex-icon fa-cogs


requires:
    redaxo: '^5.0'
    packages:
        yform: '^2.3'